version: 2
updates:
  - package-ecosystem: "npm"
    registries:
      - npm-local
    directory: "/"
    schedule:
      interval: "daily"
registries:
  npm-local:
    type: npm-registry
    url:  https://pkgs.dev.azure.com/DevExpressTestCafe/_packaging/testcafe-builds/npm/registry/
    username: VssSessionToken
    password: ${{ secrets.PASS }}
