name: Test

on: 
  pull_request_target:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.author_association == 'NONE' && 'insecure' || 'secure' }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: DevExpress/testcafe-build-system/actions/build@main
